----------------------------------------------------> SCRIPT - SISTEMA CAME <-------------------------------------------------------

--- TABLA AREA ---

  CREATE TABLE "CAME"."AREA" 
   (	"CODARE" NUMBER, 
	"NOMARE" VARCHAR2(50 BYTE), 
	"ABRARE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."AREA"."CODARE" IS 'Código autogenerado';
   COMMENT ON COLUMN "CAME"."AREA"."NOMARE" IS 'Nombre del área';
   COMMENT ON COLUMN "CAME"."AREA"."ABRARE" IS 'Abreviatura de área';

--- TABLA ASIGCOACH ---

  CREATE TABLE "CAME"."ASIGCOACH" 
   (	"CODASICOA" NUMBER, 
	"CODCOACH" NUMBER, 
	"CODPER" NUMBER, 
	"CODDETPROG" NUMBER, 
	"ESTASICOA" CHAR(1 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."ASIGCOACH"."CODASICOA" IS 'Código autogenerado';
   COMMENT ON COLUMN "CAME"."ASIGCOACH"."CODCOACH" IS 'Código de persona COACH';
   COMMENT ON COLUMN "CAME"."ASIGCOACH"."CODPER" IS 'Código de persona Alumno';
   COMMENT ON COLUMN "CAME"."ASIGCOACH"."CODDETPROG" IS 'Código de detalle programa';
   COMMENT ON COLUMN "CAME"."ASIGCOACH"."ESTASICOA" IS 'Estado';
   
--- TABLA ASIGMONITOR ---

  CREATE TABLE "CAME"."ASIGMONITOR" 
   (	"CODASIMON" NUMBER, 
	"CODMONITOR" NUMBER, 
	"CODPER" NUMBER, 
	"CODDETPROG" NUMBER, 
	"ESTASIMON" CHAR(1 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."ASIGMONITOR"."CODASIMON" IS 'Código Autogenerado';
   COMMENT ON COLUMN "CAME"."ASIGMONITOR"."CODMONITOR" IS 'Código del Monitor';
   COMMENT ON COLUMN "CAME"."ASIGMONITOR"."CODPER" IS 'Código del Participante';
   COMMENT ON COLUMN "CAME"."ASIGMONITOR"."CODDETPROG" IS 'Código del Detalle de Programa';
   COMMENT ON COLUMN "CAME"."ASIGMONITOR"."ESTASIMON" IS 'Estado';
   
--- DDL for Table ASIGNACION ---

  CREATE TABLE "CAME"."ASIGNACION" 
   (	"CODASIG" NUMBER(*,0), 
	"CODPER" NUMBER(*,0), 
	"CODDETPROG" NUMBER(*,0), 
	"FECREG" DATE, 
	"ESTREG" VARCHAR2(2 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."ASIGNACION"."CODASIG" IS 'Código identificador de asignación.';
   COMMENT ON COLUMN "CAME"."ASIGNACION"."CODPER" IS 'Código identificador de la persona(de tipo participante o estudiante).';
   COMMENT ON COLUMN "CAME"."ASIGNACION"."CODDETPROG" IS 'Código identificador del detalle del programa.';
   COMMENT ON COLUMN "CAME"."ASIGNACION"."ESTREG" IS 'A';
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "CAME"."AUDITORIA" 
   (	"CODAUD" NUMBER, 
	"USUARIO" VARCHAR2(250 BYTE), 
	"EVENTO" VARCHAR2(250 BYTE), 
	"VALOR" NUMBER, 
	"CODDETPRO" NUMBER, 
	"CODBIB" VARCHAR2(20 BYTE), 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BIBLIOTECA
--------------------------------------------------------

  CREATE TABLE "CAME"."BIBLIOTECA" 
   (	"CODBIB" NUMBER, 
	"NOMB" VARCHAR2(200 BYTE), 
	"TAM" VARCHAR2(20 BYTE), 
	"FECHA" DATE, 
	"TIPCON" VARCHAR2(200 BYTE), 
	"UBIC" VARCHAR2(20 BYTE), 
	"PRIV" CHAR(1 BYTE) DEFAULT 'E', 
	"CODTIPPG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."CODBIB" IS 'Codigo identificador del documento';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."NOMB" IS 'Nombre del documento';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."TAM" IS 'Tamaño del documento';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."FECHA" IS 'Fecha en la que se guardo el documento';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."TIPCON" IS 'Tipo del contenido del documento';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."UBIC" IS 'Ubicacion donde se guardara el archivo';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."PRIV" IS 'Flag para que pueda o no ver el Participante';
   COMMENT ON COLUMN "CAME"."BIBLIOTECA"."CODTIPPG" IS 'Código del tipo de programa';
--------------------------------------------------------
--  DDL for Table COACHING
--------------------------------------------------------

  CREATE TABLE "CAME"."COACHING" 
   (	"CODCOA" NUMBER, 
	"HORINI" VARCHAR2(7 BYTE), 
	"HORFIN" VARCHAR2(7 BYTE), 
	"LUGAR" VARCHAR2(400 BYTE), 
	"DESCRI" VARCHAR2(500 BYTE), 
	"CODASICOA" NUMBER, 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."COACHING"."CODCOA" IS 'Codigo Autogenerado';
   COMMENT ON COLUMN "CAME"."COACHING"."HORINI" IS 'Hora incio';
   COMMENT ON COLUMN "CAME"."COACHING"."HORFIN" IS 'Hora Fin';
   COMMENT ON COLUMN "CAME"."COACHING"."CODASICOA" IS 'Codigo de Asignacion';
--------------------------------------------------------
--  DDL for Table COMPETENCIA
--------------------------------------------------------

  CREATE TABLE "CAME"."COMPETENCIA" 
   (	"CODCOM" NUMBER, 
	"NOMCOM" VARCHAR2(100 BYTE), 
	"CODARE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONFIG_PESOS
--------------------------------------------------------

  CREATE TABLE "CAME"."CONFIG_PESOS" 
   (	"CODCONFPES" NVARCHAR2(20), 
	"CODFASE" NUMBER, 
	"PESOCASO" NVARCHAR2(20) DEFAULT '0', 
	"PESOTRA" NVARCHAR2(20) DEFAULT '0', 
	"PESOPARC" NVARCHAR2(20) DEFAULT '0', 
	"PESOFINAL" NVARCHAR2(20) DEFAULT '0', 
	"PESOPART" VARCHAR2(20 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."CODCONFPES" IS 'CÒDIGO PRIMARIO DE LA CONFIGURACIÒN DE PESOS';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."CODFASE" IS 'CÒDIGO DE LA FASE A LA QUE SE LE ASIGNARÀN LOS PESOS';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."PESOCASO" IS 'PESO DEL CASO';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."PESOTRA" IS 'PESO DEL TRABAJO';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."PESOPARC" IS 'PESO DEL EXAMEN PARCIAL';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."PESOFINAL" IS 'PESO DEL EXAMEN FINAL';
   COMMENT ON COLUMN "CAME"."CONFIG_PESOS"."PESOPART" IS 'PESO DE LA PARTICIPACION';
--------------------------------------------------------
--  DDL for Table EMPRESA
--------------------------------------------------------

  CREATE TABLE "CAME"."EMPRESA" 
   (	"CODEMP" NUMBER, 
	"RUCEMP" VARCHAR2(30 BYTE), 
	"NOMBEMP" VARCHAR2(100 BYTE), 
	"CODUBI" NUMBER, 
	"DIREMP" VARCHAR2(200 BYTE), 
	"ACTEMP" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTREVISTA
--------------------------------------------------------

  CREATE TABLE "CAME"."ENTREVISTA" 
   (	"CODENT" NUMBER, 
	"CODPER" NUMBER, 
	"FECENT" DATE, 
	"PRE1" VARCHAR2(250 BYTE), 
	"PRE2" VARCHAR2(250 BYTE), 
	"COMENT" VARCHAR2(250 BYTE), 
	"ENTREVISTADOR" NUMBER, 
	"ESTENT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FASE
--------------------------------------------------------

  CREATE TABLE "CAME"."FASE" 
   (	"CODFASE" NUMBER(*,0), 
	"CODDETPROG" NUMBER(*,0), 
	"NOMFASE" VARCHAR2(100 BYTE), 
	"ESTFASE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."FASE"."CODFASE" IS 'Código identificador de la fase.';
   COMMENT ON COLUMN "CAME"."FASE"."CODDETPROG" IS 'Código identificador del detalle del programa';
   COMMENT ON COLUMN "CAME"."FASE"."NOMFASE" IS 'Nombre de la fase.';
--------------------------------------------------------
--  DDL for Table FASE_DET
--------------------------------------------------------

  CREATE TABLE "CAME"."FASE_DET" 
   (	"CODFASDET" NUMBER(*,0), 
	"PROMFAS" FLOAT(126), 
	"CODFASE" NUMBER(*,0), 
	"CODASIG" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."FASE_DET"."CODFASDET" IS 'Código identificador del detalle de fase.';
   COMMENT ON COLUMN "CAME"."FASE_DET"."PROMFAS" IS 'Promedio final del participante al final de la fase.';
   COMMENT ON COLUMN "CAME"."FASE_DET"."CODFASE" IS 'Código identificador de la fase.';
   COMMENT ON COLUMN "CAME"."FASE_DET"."CODASIG" IS 'Código identificador de asignación(persona de tipo estudiante)';
--------------------------------------------------------
--  DDL for Table FDPROGRAMA
--------------------------------------------------------

  CREATE TABLE "CAME"."FDPROGRAMA" 
   (	"COD_FDPROG" NUMBER(38,0), 
	"PROFRPT1" VARCHAR2(1 BYTE), 
	"PROFRPT2" VARCHAR2(1 BYTE), 
	"PROFRPT3" VARCHAR2(1 BYTE), 
	"PROFRPT4" VARCHAR2(1 BYTE), 
	"PUNTRPT1" VARCHAR2(1 BYTE), 
	"PUNTRPT2" VARCHAR2(1 BYTE), 
	"AREAOPORPROF" VARCHAR2(1000 BYTE), 
	"DIRCPROGRPT1" VARCHAR2(1 BYTE), 
	"DIRCPROGRPT2" VARCHAR2(1 BYTE), 
	"TEMRPT1" VARCHAR2(1 BYTE), 
	"TEMRPT2" VARCHAR2(1 BYTE), 
	"TEMSUG" VARCHAR2(1000 BYTE), 
	"PARTRPT1" VARCHAR2(1 BYTE), 
	"PARTRPT2" VARCHAR2(1 BYTE), 
	"SESRPT" VARCHAR2(1 BYTE), 
	"SERVRPT1" VARCHAR2(1 BYTE), 
	"SERVRPT2" VARCHAR2(1 BYTE), 
	"SUGERENCIA" VARCHAR2(1000 BYTE), 
	"CODSES" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_IMP_PARC
--------------------------------------------------------

  CREATE TABLE "CAME"."F_IMP_PARC" 
   (	"CODIMPPARC" NUMBER(*,0), 
	"RPTA01" CHAR(1 BYTE), 
	"RPTA02" CHAR(1 BYTE), 
	"RPTA03" NVARCHAR2(200), 
	"RPTA07" CHAR(1 BYTE), 
	"RPTA07_1" NVARCHAR2(200), 
	"RPTA08" NVARCHAR2(200), 
	"RPTA06_1" CHAR(1 BYTE), 
	"RPTA06_2" CHAR(1 BYTE), 
	"RPTA06_3" CHAR(1 BYTE), 
	"RPTA06_4" CHAR(1 BYTE), 
	"RPTA06_5" CHAR(1 BYTE), 
	"RPTA04_1" CHAR(1 BYTE), 
	"DNIPER" CHAR(8 BYTE), 
	"CODFASE" NUMBER, 
	"FECEVAIMP" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_IMP_PARC_PROF
--------------------------------------------------------

  CREATE TABLE "CAME"."F_IMP_PARC_PROF" 
   (	"CODIMPPARPROF" NUMBER(*,0), 
	"RPTA" CHAR(1 BYTE), 
	"CODPER" NUMBER(*,0), 
	"CODIMPPARC" NUMBER(*,0), 
	"PREGUNTA" VARCHAR2(20 BYTE), 
	"DNIPER" CHAR(8 BYTE), 
	"CODFASE" NUMBER, 
	"CODSES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_IMP_PARC_SES
--------------------------------------------------------

  CREATE TABLE "CAME"."F_IMP_PARC_SES" 
   (	"CODIMPPARSES" NUMBER(*,0), 
	"RPTA" CHAR(1 BYTE), 
	"CODSES" NUMBER(*,0), 
	"CODIMPPARC" NUMBER(*,0), 
	"PREGUNTA" VARCHAR2(20 BYTE), 
	"DNIPER" CHAR(8 BYTE), 
	"CODFASE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FMONITOR
--------------------------------------------------------

  CREATE TABLE "CAME"."FMONITOR" 
   (	"CODFMON" NUMBER, 
	"ASISTENCIA" VARCHAR2(2 BYTE), 
	"ENTCASO" VARCHAR2(2 BYTE), 
	"USSEC" VARCHAR2(2 BYTE), 
	"PUNTUALIDAD" VARCHAR2(2 BYTE), 
	"PARTICIPACION" VARCHAR2(2 BYTE), 
	"OBSERVACION" VARCHAR2(300 BYTE), 
	"CODPER" NUMBER, 
	"CODSES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FPARTICIPANTE
--------------------------------------------------------

  CREATE TABLE "CAME"."FPARTICIPANTE" 
   (	"COD_FPART" NUMBER(38,0), 
	"PROFRPT" VARCHAR2(1 BYTE), 
	"PROFSUG" VARCHAR2(500 BYTE), 
	"TEMRPT" VARCHAR2(1 BYTE), 
	"TEMSUG" VARCHAR2(500 BYTE), 
	"SECORPT" VARCHAR2(1 BYTE), 
	"SECORPT1" VARCHAR2(500 BYTE), 
	"SECORPT2" VARCHAR2(500 BYTE), 
	"CASORPT1" VARCHAR2(1 BYTE), 
	"CASORPT2" VARCHAR2(1 BYTE), 
	"CASORPT3" VARCHAR2(1 BYTE), 
	"AUTRPT1" VARCHAR2(1 BYTE), 
	"AUTRPT2" VARCHAR2(1 BYTE), 
	"SERVRPT1" VARCHAR2(1 BYTE), 
	"SUGERENCIAS" VARCHAR2(1000 BYTE), 
	"QUEJAS" VARCHAR2(1000 BYTE), 
	"CODSES" NUMBER(38,0), 
	"CODASIG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FPROFESOR
--------------------------------------------------------

  CREATE TABLE "CAME"."FPROFESOR" 
   (	"COD_FPROF" NUMBER(38,0), 
	"DIREPROG1" VARCHAR2(1 BYTE), 
	"DIREPROG2" VARCHAR2(1 BYTE), 
	"DIREPROG3" VARCHAR2(1 BYTE), 
	"DIREPROG4" VARCHAR2(1 BYTE), 
	"DIREPROG5" VARCHAR2(1 BYTE), 
	"PART1" VARCHAR2(1 BYTE), 
	"PART2" VARCHAR2(1 BYTE), 
	"TEM1" VARCHAR2(1 BYTE), 
	"TEM2" VARCHAR2(1 BYTE), 
	"SUGERENCIA" VARCHAR2(1000 BYTE), 
	"CODSES" NUMBER(38,0), 
	"CODPER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACION
--------------------------------------------------------

  CREATE TABLE "CAME"."NOTIFICACION" 
   (	"CODNOT" NUMBER, 
	"CODDETPROG" NUMBER, 
	"MENNOT" VARCHAR2(100 BYTE), 
	"FECNOT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."NOTIFICACION"."CODNOT" IS 'Código identificador del registro';
   COMMENT ON COLUMN "CAME"."NOTIFICACION"."CODDETPROG" IS 'Código de detalle de programa';
   COMMENT ON COLUMN "CAME"."NOTIFICACION"."MENNOT" IS 'Mensaje de la notificación';
   COMMENT ON COLUMN "CAME"."NOTIFICACION"."FECNOT" IS 'Fecha de notificación';
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "CAME"."PAGOS" 
   (	"CODPAG" NUMBER, 
	"CODPER" NUMBER, 
	"ASUMPAG" CHAR(1 BYTE), 
	"ESTPAG" CHAR(1 BYTE), 
	"CANTDES" NUMBER(*,0), 
	"CONDPAG" VARCHAR2(200 BYTE), 
	"OBSEPAG" VARCHAR2(200 BYTE), 
	"ENCPAG" VARCHAR2(100 BYTE), 
	"EMAILENC" VARCHAR2(100 BYTE), 
	"TELFENC" VARCHAR2(20 BYTE), 
	"ADMINISTRADOR" NUMBER, 
	"FECHAREG" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGOS_DET
--------------------------------------------------------

  CREATE TABLE "CAME"."PAGOS_DET" 
   (	"CODPAGDET" NUMBER, 
	"CODPAG" NUMBER, 
	"FECPAG" DATE, 
	"MONTPAG" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "CAME"."PERSONA" 
   (	"CODPER" NUMBER(*,0), 
	"NOMPER" VARCHAR2(100 BYTE), 
	"APEPER" VARCHAR2(100 BYTE), 
	"DNIPER" CHAR(8 BYTE), 
	"EMAILPER" VARCHAR2(100 BYTE), 
	"SEXPER" CHAR(1 BYTE), 
	"CELPER" CHAR(30 BYTE), 
	"DIRPER" VARCHAR2(200 BYTE), 
	"TIPOPER" NVARCHAR2(30), 
	"ESTPER" CHAR(1 BYTE), 
	"USERPER" VARCHAR2(50 BYTE), 
	"PASSPER" VARCHAR2(50 BYTE), 
	"CODUBI" NUMBER(*,0), 
	"FECHPER" DATE, 
	"IMGPER" VARCHAR2(300 BYTE), 
	"CARGOPER" VARCHAR2(150 BYTE), 
	"CODEMP" NUMBER, 
	"LUGNAC" VARCHAR2(100 BYTE), 
	"ESTCIV" VARCHAR2(50 BYTE), 
	"PROFPER" VARCHAR2(100 BYTE), 
	"INIPER" VARCHAR2(5 BYTE), 
	"NACNLPER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."PERSONA"."CODPER" IS 'Código identificador de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."NOMPER" IS 'Nombre de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."APEPER" IS 'Apellido de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."DNIPER" IS 'Número de DNI de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."EMAILPER" IS 'Correo electrónico de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."SEXPER" IS 'Sexo de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."CELPER" IS 'Número de celular de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."DIRPER" IS 'Dirección de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."TIPOPER" IS 'Tipo de persona(administrador, director, profesor o estudiante).';
   COMMENT ON COLUMN "CAME"."PERSONA"."ESTPER" IS 'Flag de estado activo/inactivo de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."USERPER" IS 'Nombre de usuario de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."PASSPER" IS 'Contraseña de la persona.';
   COMMENT ON COLUMN "CAME"."PERSONA"."CODUBI" IS 'Código identificador del ubigeo.';
   COMMENT ON COLUMN "CAME"."PERSONA"."FECHPER" IS 'Fecha de nacimiento de la persona';
   COMMENT ON COLUMN "CAME"."PERSONA"."IMGPER" IS 'Foto de la persona';
   COMMENT ON COLUMN "CAME"."PERSONA"."CARGOPER" IS 'Cargo que ocupa dentro de la empresa el participante.';
   COMMENT ON COLUMN "CAME"."PERSONA"."CODEMP" IS 'Código identificador de la empresa donde labora el participante.';
   COMMENT ON COLUMN "CAME"."PERSONA"."LUGNAC" IS 'Lugar de nacimiento de la persona';
   COMMENT ON COLUMN "CAME"."PERSONA"."ESTCIV" IS 'Estado civil de la persona';
   COMMENT ON COLUMN "CAME"."PERSONA"."PROFPER" IS 'Profesión que desempeña la persona';
   COMMENT ON COLUMN "CAME"."PERSONA"."INIPER" IS 'Iniciales de los nombres de las personas';
--------------------------------------------------------
--  DDL for Table PERSONA_DET
--------------------------------------------------------

  CREATE TABLE "CAME"."PERSONA_DET" 
   (	"CODPERDET" NUMBER, 
	"CODPER" NUMBER, 
	"CONYUGE" VARCHAR2(100 BYTE), 
	"PROFCONY" VARCHAR2(100 BYTE), 
	"TELFTRAB" VARCHAR2(30 BYTE), 
	"EMAILTRAB" VARCHAR2(100 BYTE), 
	"AREATRAB" VARCHAR2(30 BYTE), 
	"YEARPUESTO" VARCHAR2(2 BYTE), 
	"NUMPERCARGO" VARCHAR2(3 BYTE), 
	"JEFEMP" VARCHAR2(200 BYTE), 
	"JEFCARGO" VARCHAR2(30 BYTE), 
	"JEFTELF" VARCHAR2(30 BYTE), 
	"JEFEMAIL" VARCHAR2(100 BYTE), 
	"ACTPER" VARCHAR2(450 BYTE), 
	"AUTOPER" CHAR(1 BYTE), 
	"MARCAUT" VARCHAR2(30 BYTE), 
	"PLACAUT" VARCHAR2(30 BYTE), 
	"SEGURO" VARCHAR2(100 BYTE), 
	"TELFSEGURO" VARCHAR2(30 BYTE), 
	"EMERNOMB" VARCHAR2(100 BYTE), 
	"EMERTELF" VARCHAR2(30 BYTE), 
	"IMGORG" VARCHAR2(100 BYTE), 
	"GRAPER" VARCHAR2(100 BYTE), 
	"UNIPER" VARCHAR2(100 BYTE), 
	"ESPPER" VARCHAR2(100 BYTE), 
	"PROACA1" VARCHAR2(100 BYTE), 
	"DURACA1" VARCHAR2(100 BYTE), 
	"INSACA1" VARCHAR2(100 BYTE), 
	"PROACA2" VARCHAR2(100 BYTE), 
	"DURACA2" VARCHAR2(100 BYTE), 
	"INSACA2" VARCHAR2(100 BYTE), 
	"PROACA3" VARCHAR2(100 BYTE), 
	"DURACA3" VARCHAR2(100 BYTE), 
	"INSACA3" VARCHAR2(100 BYTE), 
	"CO1" CHAR(1 BYTE), 
	"CO2" CHAR(1 BYTE), 
	"CO3" CHAR(1 BYTE), 
	"CO4" CHAR(1 BYTE), 
	"CO5" CHAR(1 BYTE), 
	"INT1" CHAR(1 BYTE), 
	"INT2" CHAR(1 BYTE), 
	"INT3" CHAR(1 BYTE), 
	"INT4" CHAR(1 BYTE), 
	"INT5" CHAR(1 BYTE), 
	"ENVIODATOS" CHAR(1 BYTE), 
	"GERENCIA" VARCHAR2(20 BYTE), 
	"JEFATURA" VARCHAR2(20 BYTE), 
	"SUPERVISOR" VARCHAR2(20 BYTE), 
	"AUTORIZACION" VARCHAR2(20 BYTE), 
	"DOCCV" VARCHAR2(1000 BYTE), 
	"NIVJER" VARCHAR2(100 BYTE), 
	"RESCUV" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CODPERDET" IS 'Código identificador de detalle persona';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CODPER" IS 'Código de la persona';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."TELFTRAB" IS 'Telefono de trabajo del participante';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."JEFEMP" IS 'Nombre del jefe del participante';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."AUTOPER" IS 'Tiene auto el participante(SI/NO)';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."IMGORG" IS 'Nombre del archivo de organigrama';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."GRAPER" IS 'Grado de estudios del participante';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INSACA1" IS 'Institucion en que se realizo el programa1';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INSACA2" IS 'Institucion en que se realizo el programa2';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."DURACA3" IS 'Duracion del programa3';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CO1" IS 'Conocimiento Comercial/Marketing';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CO2" IS 'Conocimiento Operaciones/Logística';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CO3" IS 'Conocimiento Recursos Humanos';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CO4" IS 'Conocimiento Contabilidad/Finanzas';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."CO5" IS 'Conocimiento Dirección/Liderazgo';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INT1" IS 'Interes Comercial/Marketing';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INT2" IS 'Interes Operaciones/Logística';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INT3" IS 'Interes Recursos Humanos';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INT4" IS 'Interes Contabilidad/Finanzas';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."INT5" IS 'Interes Dirección/Liderazgo';
   COMMENT ON COLUMN "CAME"."PERSONA_DET"."ENVIODATOS" IS 'Envia datos si los desea el participante(SI-1/No-0)';
--------------------------------------------------------
--  DDL for Table PERSONA_HIJOS
--------------------------------------------------------

  CREATE TABLE "CAME"."PERSONA_HIJOS" 
   (	"CODHIJ" NUMBER, 
	"CODPERDET" NUMBER, 
	"SEXHIJ" CHAR(1 BYTE), 
	"FECNACHI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROG_DET
--------------------------------------------------------

  CREATE TABLE "CAME"."PROG_DET" 
   (	"CODDETPROG" NUMBER(*,0), 
	"FECHINI" DATE, 
	"FECHFIN" DATE, 
	"ESTDETPROG" CHAR(1 BYTE) DEFAULT 'E', 
	"GENDETPROG" VARCHAR2(10 BYTE), 
	"CODPER" NUMBER(*,0), 
	"CODPROG" NUMBER(*,0), 
	"FRECDETPROG" VARCHAR2(20 BYTE), 
	"HORINIFIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."PROG_DET"."CODDETPROG" IS 'Código identificador del detalle del programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."FECHINI" IS 'Fecha de inicio de un programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."FECHFIN" IS 'Fecha final de un programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."ESTDETPROG" IS 'Flag de estado activo/inactivo del detalle del programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."GENDETPROG" IS 'Número de la generación del programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."CODPER" IS 'Código identificador de la persona(de tipo participante o estudiante).';
   COMMENT ON COLUMN "CAME"."PROG_DET"."CODPROG" IS 'Código identificador del programa.';
   COMMENT ON COLUMN "CAME"."PROG_DET"."FRECDETPROG" IS 'Frecuencia del programa';
   COMMENT ON COLUMN "CAME"."PROG_DET"."HORINIFIN" IS 'Hora de inicio y fin en general de cada sesión';
--------------------------------------------------------
--  DDL for Table PROGRAMA
--------------------------------------------------------

  CREATE TABLE "CAME"."PROGRAMA" 
   (	"CODPROG" NUMBER(*,0), 
	"NOMPROG" VARCHAR2(200 BYTE), 
	"ESTPROG" CHAR(1 BYTE) DEFAULT 'A', 
	"CODTIPPG" NUMBER(*,0), 
	"INIPROG" VARCHAR2(20 BYTE), 
	"CODARE" NUMBER, 
	"CODEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."PROGRAMA"."CODPROG" IS 'Código identificador del programa.';
   COMMENT ON COLUMN "CAME"."PROGRAMA"."NOMPROG" IS 'Nombre del programa.';
   COMMENT ON COLUMN "CAME"."PROGRAMA"."ESTPROG" IS 'Flag de estado activo/inactivo del programa.';
   COMMENT ON COLUMN "CAME"."PROGRAMA"."CODTIPPG" IS 'Código identificador del tipo de programa.';
   COMMENT ON COLUMN "CAME"."PROGRAMA"."INIPROG" IS 'Abrebiación del programa';
   COMMENT ON COLUMN "CAME"."PROGRAMA"."CODARE" IS 'Codigo de Area';
--------------------------------------------------------
--  DDL for Table SESION
--------------------------------------------------------

  CREATE TABLE "CAME"."SESION" 
   (	"CODSES" NUMBER(*,0), 
	"NOMSES" VARCHAR2(100 BYTE), 
	"DECSES" VARCHAR2(500 BYTE), 
	"ASISTENCIA" CHAR(1 BYTE) DEFAULT 'A', 
	"PARTICIPACION" CHAR(1 BYTE) DEFAULT '0', 
	"CASO" CHAR(1 BYTE) DEFAULT '0', 
	"CONTROL" CHAR(1 BYTE) DEFAULT '0', 
	"EXAMPARC" CHAR(1 BYTE) DEFAULT '0', 
	"EXAMFINAL" CHAR(1 BYTE) DEFAULT '0', 
	"TRABAJO" CHAR(1 BYTE) DEFAULT '0', 
	"CODFASE" NUMBER(*,0), 
	"TIPSES" VARCHAR2(3 BYTE) DEFAULT 'I', 
	"CODPROF" NUMBER, 
	"FECHASES" DATE, 
	"CASO2" CHAR(1 BYTE) DEFAULT '0', 
	"LINK_PART" VARCHAR2(250 BYTE), 
	"LINK_MONITOR" VARCHAR2(250 BYTE), 
	"LINK_DIREC" VARCHAR2(250 BYTE), 
	"LINK_PROF" VARCHAR2(250 BYTE), 
	"HORA_INI" TIMESTAMP (6), 
	"HORA_FIN" TIMESTAMP (6), 
	"MODOSES" VARCHAR2(2 BYTE), 
	"CODCOM" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."SESION"."CODSES" IS 'CODSES es el codigo sesion de la para identificar la sesion.
';
   COMMENT ON COLUMN "CAME"."SESION"."NOMSES" IS 'NOMSES de la sesion es para identificar el nombre de la sesion';
   COMMENT ON COLUMN "CAME"."SESION"."DECSES" IS 'DECSES es el campo donde se pondra la descripcion de la sesion.';
   COMMENT ON COLUMN "CAME"."SESION"."ASISTENCIA" IS 'ASISTENCIA es el campo el cual ira A o I si es quieres habilitarse para que no sume los criterios';
   COMMENT ON COLUMN "CAME"."SESION"."PARTICIPACION" IS 'Participacion es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."CASO" IS 'CASO es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."CONTROL" IS 'CONTROL es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."EXAMPARC" IS 'EXAMPARC es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."EXAMFINAL" IS 'EXAMFINAL es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."TRABAJO" IS 'TRABAJO es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."CODFASE" IS 'ASISTENCIA es el campo el cual ira 0 o 1 si es quieres habilitarse';
   COMMENT ON COLUMN "CAME"."SESION"."TIPSES" IS 'TIPSES es el campo en el cual ira si es normal final o trabajo';
   COMMENT ON COLUMN "CAME"."SESION"."CODPROF" IS 'CODPROF es el campo en el cual ira el ID del profesor por el cual se identificara que profesor dicto la sesion';
   COMMENT ON COLUMN "CAME"."SESION"."FECHASES" IS 'FECHASES  es el campo en el cual la fecha en que se dio la sesion';
   COMMENT ON COLUMN "CAME"."SESION"."LINK_PART" IS 'Link del formulario del participante.';
   COMMENT ON COLUMN "CAME"."SESION"."LINK_MONITOR" IS 'Link del formulario del monitor';
   COMMENT ON COLUMN "CAME"."SESION"."LINK_DIREC" IS 'Link del formulario del director de programa.';
   COMMENT ON COLUMN "CAME"."SESION"."LINK_PROF" IS 'Link del formulario del profesor.';
   COMMENT ON COLUMN "CAME"."SESION"."HORA_INI" IS 'Hora de inicio de la sesión';
   COMMENT ON COLUMN "CAME"."SESION"."HORA_FIN" IS 'Hora de finalización de la sesión';
   COMMENT ON COLUMN "CAME"."SESION"."MODOSES" IS 'Modo de la sesión(Presencial o semi-presencial)';
   COMMENT ON COLUMN "CAME"."SESION"."CODCOM" IS 'Código de la competencia de la sesión';
--------------------------------------------------------
--  DDL for Table SESION_ACT
--------------------------------------------------------

  CREATE TABLE "CAME"."SESION_ACT" 
   (	"CODSESACT" NUMBER, 
	"HORAINI" VARCHAR2(10 BYTE), 
	"HORAFIN" VARCHAR2(10 BYTE), 
	"CODSES" NUMBER, 
	"DESCACT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."SESION_ACT"."HORAINI" IS 'Hora de inicio de la actividad';
   COMMENT ON COLUMN "CAME"."SESION_ACT"."CODSES" IS 'Código identificador de la sesión';
   COMMENT ON COLUMN "CAME"."SESION_ACT"."DESCACT" IS 'Descripción de la actividad a realizar en la sesión';
--------------------------------------------------------
--  DDL for Table SESION_ANEXO
--------------------------------------------------------

  CREATE TABLE "CAME"."SESION_ANEXO" 
   (	"CODSESANE" NUMBER, 
	"CODSES" NUMBER, 
	"CODBIB" NUMBER, 
	"FECSESANE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."SESION_ANEXO"."CODSES" IS 'CODIGO DE LA SESION';
   COMMENT ON COLUMN "CAME"."SESION_ANEXO"."CODBIB" IS 'CODIGO DE LA BIBLIOTECA';
   COMMENT ON COLUMN "CAME"."SESION_ANEXO"."FECSESANE" IS 'FECHA DE ANEXADO DOCUMENTO';
--------------------------------------------------------
--  DDL for Table SESION_DET
--------------------------------------------------------

  CREATE TABLE "CAME"."SESION_DET" 
   (	"CODDETSES" NUMBER(*,0), 
	"CODSES" NUMBER(*,0), 
	"ASISTENCIA" CHAR(1 BYTE), 
	"PARTICIPACION" NUMBER(*,0), 
	"CASO" NUMBER(*,0), 
	"CONTROL" NUMBER(*,0), 
	"EXAMPARC" NUMBER(*,0), 
	"EXAMFINAL" NUMBER(*,0), 
	"TRABAJO" NUMBER(*,0), 
	"PROMEDIOS" FLOAT(126), 
	"CODASIG" NUMBER, 
	"CASO2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."SESION_DET"."CODDETSES" IS 'Código identificador del detalle de la sesión.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."CODSES" IS 'Código identificador de la sesión.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."ASISTENCIA" IS 'Asistencia del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."PARTICIPACION" IS 'Nota de particicipacion.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."CASO" IS 'Nota del caso del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."CONTROL" IS 'Nota de control del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."EXAMPARC" IS 'Nota de examen parcial del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."EXAMFINAL" IS 'Nota de examen final del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."TRABAJO" IS 'Nota de trabajo del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."PROMEDIOS" IS 'Promedio de la sesión del participante.';
   COMMENT ON COLUMN "CAME"."SESION_DET"."CODASIG" IS 'Código identificador de asignación del participante.';
--------------------------------------------------------
--  DDL for Table TIPOPROG
--------------------------------------------------------

  CREATE TABLE "CAME"."TIPOPROG" 
   (	"CODTIPPG" NUMBER(*,0), 
	"NOMTIPOPG" VARCHAR2(100 BYTE), 
	"ESTTIPOPG" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."TIPOPROG"."CODTIPPG" IS 'Código identificador del tipo de programa.';
   COMMENT ON COLUMN "CAME"."TIPOPROG"."NOMTIPOPG" IS 'Nombre del tipo de programa.';
   COMMENT ON COLUMN "CAME"."TIPOPROG"."ESTTIPOPG" IS 'Flag de estado activo/inactivo del tipo de programa.';
--------------------------------------------------------
--  DDL for Table UBIGEO
--------------------------------------------------------

  CREATE TABLE "CAME"."UBIGEO" 
   (	"CODUBI" NUMBER(*,0), 
	"DEPUBI" VARCHAR2(50 BYTE), 
	"PROVUBI" VARCHAR2(50 BYTE), 
	"DISTUBI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAME"."UBIGEO"."CODUBI" IS 'Código identificador del ubigeo.';
   COMMENT ON COLUMN "CAME"."UBIGEO"."DEPUBI" IS 'Departamento.';
   COMMENT ON COLUMN "CAME"."UBIGEO"."PROVUBI" IS 'Provincia.';
   COMMENT ON COLUMN "CAME"."UBIGEO"."DISTUBI" IS 'Distrito.';
   
--------------------------------------------------------





----------------------------------------------------> RELATIONS - SISTEMA CAME <---------------------------------------------------
